### ISSUE TITLE
GET request on refresh-token viewset with anonymous user results in server error

### ISSUE THREAD

**Issue by PeteAndersen** [lock8/django-rest-framework-jwt-refresh-token#11]
The [get_queryset() method of RefreshTokenViewSet](https://github.com/lock8/django-rest-framework-jwt-refresh-token/blob/master/refreshtoken/views.py#L62) assumes users are authenticated. When accessing request.user you'll get back an AnonymousUser object which has an ID of None and causes the error trying to filter on it. 

I can submit a PR to fix it but I wanted to get your thoughts on the best action to take. I am thinking a 401 Unauthorized when making unauthorized GET requests makes the most sense.

**Comment by porksmash** [comment]
Actually, just implementing IsAuthorized DRF permission class for the entire viewset is ideal. Creating a token assumes user is already authenticated. Unfortunately still have to edit get_queryset() to check for is_authenticated because it runs regardless if permissions reject the request.

**Comment by blueyed** [comment]
Thanks for bringing this up.
@ticosax is currently not available, and I am not sure myself what is best here.

Feel free to create a PR already with what you think is best to get the ball rolling.
Thanks!

**Comment by ticosax** [comment]
This must be configurable through the default permission_classes.
http://www.django-rest-framework.org/api-guide/settings/#default_permission_classes
