### ISSUE TITLE
How to exchange refresh token for new JWT 

### ISSUE THREAD

**Issue by ReeceHumphreys** [lock8/django-rest-framework-jwt-refresh-token#27]
I have successfully logged in and now have a JWT token and a refresh token. What is the URL endpoint for exchanging a refresh token for a new JWT once the JWT is expired? I have tried` /delegate` and `/refresh-token` but cannot get it to work.

**Comment by ticosax** [comment]
This is `delegate`. like explained in the README
https://github.com/lock8/django-rest-framework-jwt-refresh-token#usage

**Comment by renefs** [comment]
I think that's not right. If you check the url paths, there is none called 'delegate'. There is one called /refresh-token/.

**Comment by renefs** [comment]
In fact:
`urlpatterns = router.urls + [
    url(r'^delegate/$', DelegateJSONWebToken.as_view(),
        name='delegate-tokens'),
]`

is defined on the tests folder. Is that right? Looks strange to me

**Comment by ticosax** [comment]
Yes, that's what is missing in the doc. Would you mind make a PR to fix it ?

**Comment by renefs** [comment]
No problem 👍 but I am missing some behavior. The first time I go to `/api-token-auth/` the refresh_token is null (the access token is correct). What must be done in order to get the refresh_token the first time?

**Comment by ReeceHumphreys** [comment]
Yes, @renefs  is correct to resolve the issue I had to add the extra URL patterns that were not in the docs.

**Comment by ticosax** [comment]
Let's keep it open until the doc is updated accordingly.

**Comment by blueyed** [comment]
@renefs 
You have to create an initial refresh token when the user gets registered.

**Comment by MihaiVisu** [comment]
So how do I create the initial refresh token for the user in a clean way? I still get refresh_token null.
