### ISSUE TITLE
Example on How to use this Plugin to Obtain a Refresh Token

### ISSUE THREAD

**Issue by sethwhite2** [lock8/django-rest-framework-jwt-refresh-token#6]
I ran across this plugin when trying to set up DRF JWT to have a long lasting refresh token and short lived access tokens.

The documentation is clear on the setup and usage of this plugin. But it is not clear on how to use this plugin to obtain/create a refresh token.

Can anyone help me understand how I'm supposed to use this plugin to obtain/create a refresh token?

Thanks!

**Comment by ticosax** [comment]
Hi @sethwhite2, 
Sorry for the late reply I was away.
To answer your question there is no *one*  obvious way to create the refresh token, it is entirely up to you you and your business logic.

To give you an example it is simple as this.

```python
user.refresh_tokens.create(app=name_of_your_app)
```

Where you call it ? is up to you.

**Comment by blueyed** [comment]
Should this be added to the documentation then?

@sethwhite2 
Do you feel like creating a PR for it?

**Comment by sethwhite2** [comment]
@blueyed sure. I'll create a PR for this.
